// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY0GCiz_wdqpFQJJvyCL-2pVWEheq8Xy4',
    appId: '1:226013068859:web:2cde2e152cb9bdfb82e61e',
    messagingSenderId: '226013068859',
    projectId: 'clone-6e3f6',
    authDomain: 'clone-6e3f6.firebaseapp.com',
    storageBucket: 'clone-6e3f6.appspot.com',
    measurementId: 'G-B5LKEYHD0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmhpTGITStc7aWbiIbSRrg5TbzQ73NM4',
    appId: '1:226013068859:android:25009f9da4d2dce482e61e',
    messagingSenderId: '226013068859',
    projectId: 'clone-6e3f6',
    storageBucket: 'clone-6e3f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGiYXoQ82rNVlA4oPX8xEuuaZizdbXkyY',
    appId: '1:226013068859:ios:90c76c1a482f7b0382e61e',
    messagingSenderId: '226013068859',
    projectId: 'clone-6e3f6',
    storageBucket: 'clone-6e3f6.appspot.com',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGiYXoQ82rNVlA4oPX8xEuuaZizdbXkyY',
    appId: '1:226013068859:ios:90c76c1a482f7b0382e61e',
    messagingSenderId: '226013068859',
    projectId: 'clone-6e3f6',
    storageBucket: 'clone-6e3f6.appspot.com',
    iosBundleId: 'com.example.youtube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY0GCiz_wdqpFQJJvyCL-2pVWEheq8Xy4',
    appId: '1:226013068859:web:90d3c3aab41993b982e61e',
    messagingSenderId: '226013068859',
    projectId: 'clone-6e3f6',
    authDomain: 'clone-6e3f6.firebaseapp.com',
    storageBucket: 'clone-6e3f6.appspot.com',
    measurementId: 'G-Q8JX1EN1EY',
  );
}
